// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_-wEKYzjhtRVphrndNPCAzZ-PNBlWwrY',
    appId: '1:267885782991:web:794d123f36e4ff3ee514ba',
    messagingSenderId: '267885782991',
    projectId: 'fir-auth-bfed9',
    authDomain: 'fir-auth-bfed9.firebaseapp.com',
    storageBucket: 'fir-auth-bfed9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfZvCu5wkDY2RZUwdoXwsaKt7_2dX9HdA',
    appId: '1:267885782991:android:7c70565560c3fc4de514ba',
    messagingSenderId: '267885782991',
    projectId: 'fir-auth-bfed9',
    storageBucket: 'fir-auth-bfed9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYyWsjVIJ9nambCu15onMVZ9vzREDqja8',
    appId: '1:267885782991:ios:bd4fbc0c57fea54ae514ba',
    messagingSenderId: '267885782991',
    projectId: 'fir-auth-bfed9',
    storageBucket: 'fir-auth-bfed9.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYyWsjVIJ9nambCu15onMVZ9vzREDqja8',
    appId: '1:267885782991:ios:bd4fbc0c57fea54ae514ba',
    messagingSenderId: '267885782991',
    projectId: 'fir-auth-bfed9',
    storageBucket: 'fir-auth-bfed9.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_-wEKYzjhtRVphrndNPCAzZ-PNBlWwrY',
    appId: '1:267885782991:web:2feb0aea20d15eb6e514ba',
    messagingSenderId: '267885782991',
    projectId: 'fir-auth-bfed9',
    authDomain: 'fir-auth-bfed9.firebaseapp.com',
    storageBucket: 'fir-auth-bfed9.firebasestorage.app',
  );
}
